### ISSUE TITLE
Timer in tab

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#146]
New system should replicate the existing site. The site's title should be the time passed until the end of the time session where the tab will flash and say "time is up", until they hit complete task or reset time.

**Comment by L8D** [comment]
Apparently browsers hate intervals that run in other tabs...

**Comment by L8D** [comment]
@GarrethDottin says it's ok.

**Comment by garrethdev** [comment]
<img width="1280" alt="screen shot 2015-07-07 at 5 59 24 pm" src="https://cloud.githubusercontent.com/assets/5047981/8558339/76d52f16-24d1-11e5-86fd-b49b3f61ecb6.png">
should only show timer in tab if the time is in session otherwise it should say GrooveOtter

**Comment by ZambiBambi** [comment]
not sure if its my browser or not, have to test on browser stack but this keeps happening, it switches the tab title when i move the mouse around the app

![untitled1](https://cloud.githubusercontent.com/assets/13108339/8632040/a3ec6a3e-27cc-11e5-976b-4c2fad14c66f.jpg)

**Comment by L8D** [comment]
@ZambiBambi I noticed this too. Are you seeing it display the URL for long periods of time? I only see it flash for less than half a second at a time though.

Either way, that is because we are re-rendering the text nearly 10 times a second, and browsers animation frames are separate from the page titles. If we make a change to the title, and more browser events fire (like mouse movement) before the browser runs an animation frame (60 times a second) then it will display the URL instead of the title until the animation frame is run.

**Comment by L8D** [comment]
@ZambiBambi should be fixed once 669de5f goes live on heroku

**Comment by ZambiBambi** [comment]
@L8D yes, only flashes (was hard to capture) but okay, so it should be good then
