### ISSUE TITLE
Implement New Skin

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#148]
The designs should reflect the designs in Google Drive 
   Current Issues: 
   -Archive images should not be cutoff 
   -Clock on Archive tab should be changed to new color 
   -hover state for start and complete task need to be changed
   -New Font
   -Properly sized Logo
   -Font Weight for task area buttons

**Comment by Ryan-Parker** [comment]
The like feature on the newsfeed also needs to reflect the new brand green

**Comment by garrethdev** [comment]
Logo should be smaller

**Comment by ZambiBambi** [comment]
only happens in Firefox, time is cut of on stored tasks in the today section

![capture](https://cloud.githubusercontent.com/assets/13108339/8763750/0a057fc6-2df0-11e5-8ceb-d583686d5427.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13108339/8763751/0ff556f4-2df0-11e5-985d-dd2e27950891.PNG)

not sure if i should comment this here, i wont reopen this ticket because of that reason

**Comment by Ryan-Parker** [comment]
@ZambiBambi Please create a new ticket for this
