### ISSUE TITLE
Fix time input system

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#20]
When you double click outside the circle it should return to the timer view. Also there should be a pencil feature that appears when you mouse over. Additionally the current time should appear when you double click it. 

Criteria: 
1. Clicking outside the circle should return to original state
2. Pencil with hover state 
3. Current Time should appear in the box when they enter the edit stage
4.  Input Circle with background faded out

https://projects.invisionapp.com/share/422BZ1OQ7#/screens/67618201?maintainScrollPosition=false

**Comment by L8D** [comment]
Could you merge #19 into this? Also, does that mean if you double click
anywhere it reverts back to the wheel?

**Comment by garrethdev** [comment]
Yea will do, when you click outside the circle of the time wheel it should revert back to showing the original timer

**Comment by L8D** [comment]
From the QA

The dilemna is that I was uncertain how to edit the timer. Only after looking at the wires did I realize that I needed to click/double click the timer.

Suggestions
1. Always have an edit button visible(rather than hover-state in the wires) for editing the time so that the user does not have issues finding it.

Bugs
1. The timer required a double-click(sometimes more) to go into edit mode, the comps needed only a single click.
2. I do not know how to leave the timer edit mode without making changes. 
3. Circle missing after entering edit timer.
4. Edit timer should have min included.
5. Edit timer should not have arrows for increasing/decreasing time.
6. After entering a number in timer box and clicking Start task does not display the timer clock.

Questions
1. Do I make note(or add To-do tasks) of every little difference compared to wires?
2. There are differences between wires and the demo, such as the wording of Reset Timer, which is correct?
