### ISSUE TITLE
Fix Like Button

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#245]
Current Behavior: 
When a user likes an item, it doesn’t reflect on the UI and they are unable to like anything 

Expected Behavior: 
When a user likes an item it should change the count of items liked and it should change the item to green.

**Comment by L8D** [comment]
https://github.com/GrooveOtter/grooveotter-client/pull/238

**Comment by Ryan-Parker** [comment]
@L8D When I tested that PR I didn't see the issue resolved.

**Comment by L8D** [comment]
@Ryan-Parker yep, I think I figured out why.

To whoever is going to fix this: The current bug on #238 is that the task's from newsfeed items are pointing to `/api/tasks/:task_id` instead of `/api/newsfeed/:task_id` (which will handle public tasks). To fix this, you'll need to add a 'urlRoot' option when initializing the tasks when parsing newsfeed items [here](https://github.com/GrooveOtter/grooveotter-client/blob/master/scripts/models/notification.js#L14). Something like: `new Task(attrs.task, {parse: true, urlRoot: '/api/newsfeed'})`

**Comment by garrethdev** [comment]
The current bug on #238 is that the task's from newsfeed items are pointing to /api/tasks/:task_id instead of /api/newsfeed/:task_id (which will handle public tasks). To fix this, you'll need to add a 'urlRoot' option when initializing the tasks when parsing newsfeed items here. Something like: new Task(attrs.task, {parse: true, urlRoot: '/api/newsfeed'})

**Comment by L8D** [comment]
@GarrethDottin @devicodev The links got messed up in the copy/paste.

You'll need to add the urlRoot flag here: https://github.com/GrooveOtter/grooveotter-client/blob/master/scripts/models/notification.js#L14
